name = "MetaConfigurations"
uuid = "b3204efc-440b-4852-a818-08d33e4dcc95"
authors = ["Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>"]
version = "0.1.4"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
JSON = "0.21"
YAML = "^0.4.6"
julia = "1"

[extras]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrderedCollections", "Test"]
