name = "MetaConfigurations"
uuid = "b3204efc-440b-4852-a818-08d33e4dcc95"
authors = ["Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>"]
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
